services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    volumes:
      - ./unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
    networks:
      dns_net:
        ipv4_address: 10.10.10.2

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - "127.0.0.2:53:53/tcp"
      - "127.0.0.2:53:53/udp"
      - "127.0.0.2:80:80/tcp"
    environment:
      TZ: "Europe/Berlin"
      FTLCONF_webserver_api_password: "${PIHOLE_PASSWORD}"
      FTLCONF_dns_upstreams: "10.10.10.2#53"
      FTLCONF_dns_dnssec: "false"
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      dns_net:
        ipv4_address: 10.10.10.3
    depends_on:
      - unbound

networks:
  dns_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
